"""
FastAPI application factory and global middleware configuration.

This module is responsible for creating and configuring the FastAPI application,
including dependency wiring, request logging, centralized exception handling,
and route registration.

Responsibilities:
    - Create and configure the FastAPI app instance
    - Wire logger dependency overrides
    - Register API routes
    - Provide global middleware for logging and error handling
"""

import logging

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import JSONResponse

from . import deps, routes


def create_api(logger: logging.Logger) -> FastAPI:
    """
    Create and configure the FastAPI application.

    This function initializes the FastAPI app, wires dependency overrides,
    registers routes, and installs middleware for request logging and
    centralized exception handling.

    Args:
        logger (logging.Logger): Logger instance used for request logging
            and error reporting across the application.

    Returns:
        FastAPI: A fully configured FastAPI application instance.

    Middleware:
        - Logs all incoming HTTP requests.
        - Catches HTTPException instances and returns a structured JSON response.
        - Catches unhandled exceptions and returns a generic 500 response.

    Notes:
        - The logger dependency used in route handlers is overridden here
          using FastAPI's dependency override mechanism.
        - All API routes are registered via `routes.append_routes`.
    """
    app = FastAPI()
    app.dependency_overrides[routes.get_logger] = deps.get_logger_dep(logger)

    @app.middleware("http")
    async def logging_exception_middleware(request: Request, call_next):
        """
        Middleware for request logging and centralized exception handling.

        Logs incoming requests and ensures that all exceptions are converted
        into consistent JSON error responses.

        Args:
            request (Request): Incoming HTTP request.
            call_next (Callable): Next middleware or route handler.

        Returns:
            Response: HTTP response, either from the route handler or an
            error response generated by this middleware.

        Error Handling:
            - HTTPException: Returns the original status code and detail.
            - Unhandled Exception: Returns HTTP 500 with a generic error message.
        """
        logger.info(f"Request: {request.method} {request.url}")

        try:
            response = await call_next(request)
            return response
        except HTTPException as exc:
            logger.error(f"HTTPException: {exc.status_code} {exc.detail}", exc_info=True)
            return JSONResponse(
                status_code=exc.status_code,
                content={
                    "error": {
                        "code": exc.status_code,
                        "detail": exc.detail,
                    }
                },
            )

        except Exception as exc:
            logger.error(f"Exception: {exc.__class__.__name__}", exc_info=True)
            return JSONResponse(
                status_code=500,
                content={
                    "error": {
                        "code": 500,
                        "detail": "An unhandled exception occurred.",
                    }
                },
            )

    routes.append_routes(app)
    return app
